#请勿随意更改版本号！！！！
config-version: 6 #config.yml的版本号检测
menu-version: 1 #test.yml的版本号检测

settings:
  default-menu: "test" #必须修改为其他 test文件会默认被更改 你可以根据模板改完修改文件名进行修改

  hot-reload: # 启用后，插件会实时监控 java_menus 和 bedrock_menus 目录下的文件变化。
    enabled: true # 当文件被保存时，无需重启服务器，配置会自动重新加载。

  # 自动生成示例文件开关
  # true  = 插件启动时检测并自动生成 test.yml（仅当文件不存在时生成，只会生成一次）
  # false = 完全跳过示例文件生成逻辑，不检查也不生成
  auto-generate-examples: true

  menu-clock:
    enabled: true # 是否启用整个钟表功能
    give-on-join: true # 会检测背包中是否已有钟表，避免重复发放。

# 支持颜色代码：使用 & 符号（例如 &a 代表绿色，&c 代表红色）。
messages:
  message:
    no-permission: "&c你没有权限执行此命令!"
    players-only: "&c只有玩家才能执行此命令!"
    menu-not-found: "&c菜单不存在: "
    open-error: "&c打开菜单时发生错误，请检查控制台。"
    invalid-player: "&c玩家不存在或不在线!"
    config-update-warning: "&e检测到配置文件版本过低，正在自动更新..."
    config-updated: "&a配置文件已更新至最新版。"
    reloaded: "&a配置重载完成!"

  help:
    header: "&6=== &e你好喵&6==="
    usage: "&7鼠标悬停查看详情，点击即可执行命令"

  descriptions:
    open: "&a打开指定的菜单文件"
    reload: "&c重载插件的配置文件"
    help: "&e显示此帮助信息"

  command:
    unknown: "&c未知的子命令，使用 /dgm help 查看帮助。"
    usage-open: "&c用法: /dgm open <菜单名称>"

  menu:
    clock:
      name: "&6菜单钟表 &7(右键打开)"
      given: "&a已收到菜单钟表，右键即可打开菜单!"
      restored: "&f你的物品已恢复。"

  hot-reload:
    initialized: "菜单检测自重载已启动."
    detected: "检测到文件变更: {0}，正在重载菜单..."